name: dexterous_cheers

task_name: cheers
#修改之处
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [512, 3]
      type: point_cloud
    agent_pos:
      shape: [24]
      type: low_dim
  action:
    shape: [28]

env_runner:
  _target_: diffusion_policy_3d.env_runner.dexterous_runner.DexterousRunner
  eval_episodes: 20
  max_steps: 300
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  task_name: cheers
  render_size: 84
  use_point_crop: ${policy.use_point_crop}

dataset:
  _target_: diffusion_policy_3d.dataset.dexterous_dataset.DexterousDataset
  zarr_path: data/dexterous_cheers_expert.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
